version: "2"

services:
  novnc:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-6080:6080}"
#    volumes:
#      - ./token.conf:/noVNC/token.conf
#    environment:
#      REMOTE_HOST: 
#      REMOTE_PORT: 

